import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import QueryProvider from "./providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Toaster
            position="top-right"
            expand
            duration={2000}
            closeButton
            toastOptions={{
              classNames: {
                icon: "w-[38px] flex justify-center",
                content: "pr-4",
                closeButton:
                  "left-auto right-0 -translate-x-2/4 -translate-y-2/4 top-2/4",
              },
            }}
          />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
